### ISSUE TITLE
File index_m.html not found

### ISSUE THREAD

**Issue by kilian-f-za** [o0shojo0o/ioBroker.adguard#332]
Ich habe adguard installiert und in Anschluss könnt direkt die Meldung File index_m.html not found. Was kann ich tun?

js-controller: 4.0.23
Admin: 5.3.8

**Comment by o0shojo0o** [comment]
Der Adapter unterstützt nur die neue Oberfläche des Admin.

**Comment by kilian-f-za** [comment]
Vielen Dank. Jetzt funktioniert es. Ich hatte bis jetzt immernoch die alte Oberfläche, weil es bei manchen Adapter zu Problemen kam.
