### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by duczz** [o0shojo0o/ioBroker.adguard#424]
Hallo,

könnte man einen OID mit einbauen, der darüber Informiert wenn ein Update zur Verfügung stünde?
![image](https://user-images.githubusercontent.com/25475385/216815268-6dc089f4-bd6f-4fa6-8747-c0fd3e9b610a.png)

**Comment by nox309** [comment]
Hi, 

Ich denke, ich weiß, was du willst, aber was meinst du mit OID?

**Comment by duczz** [comment]
Eine Objekt ID 🙂

**Comment by nox309** [comment]
Okay, dann habe ich es richtig verstanden. Mal gucken, was draus wird.
