### ISSUE TITLE
Settings do not work with old Admin UI!

### ISSUE THREAD

**Issue by Dome2075** [o0shojo0o/ioBroker.adguard#43]
![image](https://user-images.githubusercontent.com/37158961/132847536-f93103f7-77e2-4e78-ace6-923958f5128f.png)

What's Wrong?

**Comment by o0shojo0o** [comment]
But it works! 
With such issues I can not start ...

**Comment by Dome2075** [comment]
Sorry the text was not published..

**Comment by o0shojo0o** [comment]
The adapter is written for the current stable state of the admin adapter, your screenshot shows the outdated admin interface. 
So the settings for the adapter is only available in the current admin interface.
