### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by Anzic23** [o0shojo0o/ioBroker.adguard#9]
**Describe the bug**  
I can't connect to the server.
**To Reproduce**  
1. install adguard docker image
2. try to connect
3. See error

**Expected behavior**  
the ability to specify not only the ip and url, but also the port.

**Screenshots & Logfiles**  
`No connection to the server could be established. (Error: Request failed with status code 403)`
**Versions:**  
 - Adapter version: 0.0.7
 - JS-Controller version: 3.3.15
 - Node version: v12.22.1
 - Operating system: docker

**Additional context**  
my configuration works in docker. Both iobroker and adguard are located in different containers. Iobroker works via macvlan with the ip address 192.168.1.100 (my network is 192.168.1.1/24). Adguard works on its network 172.23.0.0 / 16 with port forwarding to the host. Port forwarding is as follows:
0.0.0.0:4000  3000/tcp
0.0.0.0:8943  443/tcp
0.0.0.0:53  53/tcp
0.0.0.0:53  53/udp
0.0.0.0:67  67/udp
0.0.0.0:5280  80/tcp
0.0.0.0:853  853/tcp
I tried to specify the ip or url in different ways (i use revrs proxy, also), I always get the error 403. maybe it's worth adding the ability to specify the port? so that you can connect to the container.

**Comment by Anzic23** [comment]
my mistake. I used admin instead of Admin. connected. But the ability to specify the port is still desirable.

**Comment by o0shojo0o** [comment]
Hi, yes this has also happened to me :D 
Have you ever tried to specify the port in the server address, for example http://adguard:5280, that should work.
